---
- name: "Ensure iptables tooling does not use the nftables backend"
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items: "{{ configure-iptables-legacy-alternatives }}"
