---
- name: "Ensure iptables tooling does not use the nftables backend"
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items: "{{ configure_iptables_legacy_alternatives }}"
  tags:
    - "iptables-legacy"
