---
- name: "Configure iptables-legacy"
  alternatives:
    name: "{{ item.name }}"
    path: "{{ item.path }}"
  with_items: "{{ configure_iptables_legacy_alternatives[(ansible_os_family | lower) + '_' + (ansible_architecture | lower)] }}"
  tags:
    - "iptables-legacy"
